apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "myapp"
        vault.hashicorp.com/agent-inject-secret-mysql-credentials: "secret/mysql-credentials"
      labels:
        app: mysql
    spec:
      serviceAccountName: mysql-sa
      containers:
      - name: app
        image: jweissig/app:0.0.1
